### ISSUE TITLE
step files?

### ISSUE THREAD

**Issue by hanhanhan-kim** [victorlucachi/void40#2]
Hello!
Thanks for building and designing such a great 40% keyboard! I'm really enjoying it! (and am using it right now!)
I was wondering if it might be possible to ask for the solid CAD files, e.g. in `.step` format, as opposed to the mesh `.stl` files. I was thinking it might be fun to modify the design a bit so it can accept an alternative microcontroller :)
Thanks so much!

**Comment by victorlucachi** [comment]
Hey,

Thank you for the kind words. I've just added the `.step` files to the repository.
