### ISSUE TITLE
Does not fit Ender3

### ISSUE THREAD

**Issue by Lucky4Luuk** [victorlucachi/void40#7]
According to the description, it's meant to fit the Ender3 print area. But once the STL has been imported into Cura, the actual model is 236.85mm wide!

**Comment by victorlucachi** [comment]
_... when the parts are rotated 45 degrees and the skirt/brim is disabled in the slicers settings._

![image](https://github.com/user-attachments/assets/2ea50c12-0e5f-4603-b730-77e374717af5)

**Comment by Lucky4Luuk** [comment]
Oh that makes a lot of sense, awesome, thank you!

**Comment by tommyblue** [comment]
@victorlucachi I'm trying to print it in an Ender 3 V3 KE, but it doesn't fit (220x220x240). Is it supposed to work on such printer?
![image](https://github.com/user-attachments/assets/7fd70b10-0540-4eda-97d1-033f787c216a)

**Comment by victorlucachi** [comment]
> @victorlucachi I'm trying to print it in an Ender 3 V3 KE, but it doesn't fit (220x220x240). Is it supposed to work on such printer? ![image](https://private-user-images.githubusercontent.com/122749/366864746-7fd70b10-0540-4eda-97d1-033f787c216a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDM3MTQsIm5iZiI6MTcyNjE0MzQxNCwicGF0aCI6Ii8xMjI3NDkvMzY2ODY0NzQ2LTdmZDcwYjEwLTA1NDAtNGVkYS05N2QxLTAzM2Y3ODdjMjE2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxMjE2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGFmZGEzMDU3ZDFmYzVjNGViMjIyODE1ZmIyYWI1MDgyMTFhNmI2NGM3MWFhOTI5NTg1MjlmNTRlODlkNGVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vn62G1q_13A9Rb52RZoOpr97US1CmkpHfZ3jYJrPZ0k)

I have no first hand experience with that particular model, but from what I can tell it has the same 235x235mm bed; if your toolhead and nozzle can reach all four physical corners of the bed without colliding with the frame, then I would assume that it's just a matter of firmware/slicer settings.

In the screenshot that you posted there does seem to be a ~5mm keep out zone around the perimeter of the bed, if you can remove it the model should definitely fit.

**Comment by tommyblue** [comment]
oh no, it's a 220x220 bed 😢

**Comment by victorlucachi** [comment]
they're kind of lying in that regard, because the physical dimension of the build plate is 235x235mm, but you have to update your firmware and slicer settings to make use of its full size.

this is the default orca slicer profile for your printer, with the bed dimensions updated to 235x235
![image](https://github.com/user-attachments/assets/36c6695e-99f7-4fd8-8ddd-1ff936eade68)

**Comment by tommyblue** [comment]
oh, nice, I didn't know that. I'll give it a try, thanks!

**Comment by tommyblue** [comment]
Just to give you a feedback, with the Ender3 V3KE I tried enlarging the plate size to 230x230, the slicer (Prusa) is then able to fit the object and send the gcode but the printer stops when it should reach the plate limit, with a message about the coordinates being out of the printable area

**Comment by victorlucachi** [comment]
yes, that makes sense. as previously stated, you also have to adjust the bed size in your firmware.

~~I don't know if newer versions of the ender still run marlin firmware, but if the answer is yes, you have to adjust bed size in the firmware config, recompile and reflash your motherboard.~~

ah, I see, the KE in the name stands for klipper edition. klipper usually makes this kind of adjustment easy, but I know next to nothing about what creality are doing with their firmware. you will have to look into it.

**Comment by tommyblue** [comment]
oh thanks for the hint, let's see if I can brick my printer 😅

**Comment by victorlucachi** [comment]
> oh thanks for the hint, let's see if I can brick my printer 😅

I think [this](https://github.com/Guilouz/Creality-Helper-Script-Wiki) _might_ be the answer, but definitely do a bit of research on the matter. good luck!🤞
